apiVersion: v1
kind: ConfigMap
metadata:
  name: graphite-config
  labels:
    chart: sitespeed
    app: graphite
data:
  carbon.conf: |
    {{ .Files.Get "carbon.conf" | nindent 4 }}
  storage-aggregation.conf: |
    {{ .Files.Get "storage-aggregation.conf" | nindent 4 }}
  storage-schemas.conf: |
    {{ .Files.Get "storage-schemas.conf" | nindent 4 }}
