{{- if .Values.persistentVolumeClaim.create }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.results }}
  labels:
{{ toYaml .Values.customerLabels | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 10Gi
---      
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.graphite }}
  labels:
{{ toYaml .Values.customerLabels | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 2Gi
{{- end }}