apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sitespeed-throttling-proxy
  labels:
{{ toYaml .Values.customerLabels | indent 4 }}
    app: sitespeed-throttling-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitespeed-throttling-proxy
  template:
    metadata:
      labels:
{{ toYaml .Values.customerLabels | indent 8 }}
        app: sitespeed-throttling-proxy
    spec:
      serviceAccountName: graphite-sa
      containers:
      - name: sitespeed-throttling-proxy
        image: webpagetest/tsproxy
        args:
          - -v
          - --rtt=20
          - --inkbps=50000
          - --outkbps=5000
        ports:
        - name: transport
          containerPort: 1080
          protocol: TCP
        # resources:
        #   requests:
        #     cpu: "300m"
        #     memory: "512Mi"
        #   limits:
        #     cpu: "500m"
        #     memory: "768Mi"