domain: k8s.otomi.cloud
customerDomain: in.otomi.cloud

customerLabels:
  customer: otomi
  
sites: []
  # - otomi.cloud

sitespeed: []
  # - host: otomi.cloud
  #   paths: [/]

alertmanager:
  groupInterval: 5m
  repeatInterval: 3h
  
letsencrypt:
  email: "morriz@idiotz.nl"
  stage: "production"

oidc:
  grafana:
    clientId: grafana
    clientSecret: apie4eeX6hiC9ainiel1

services:
  - index
  - dashboard
  - blackbox
  - grafana
  - scope
  - prom
  - alerts
  - drone
