cluster: k8s.otomi.cloud
evCluster: k8s.otomi.cloud

sites:
  - otomi.cloud

sitespeed: 
  - host: otomi.cloud
    paths: [/]

alertmanager:
  groupInterval: 5m
  repeatInterval: 3h
  
letsencrypt:
  email: "morriz@idiotz.nl"
  stage: "production"

services:
  - index
  - blackbox
  - grafana
  - scope
  - prom
  - alerts
  - drone
