apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        policy.otomi.io/ignore-sidecar: container-limits,psp-allowed-users # <- don't remove this line as it is needed
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - env:
            - name: TARGET
              value: Knative World
          image: otomi/nodejs-helloworld:v1.2.12
