apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  labels:
    policy.otomi.io/ignore-sidecar: container-limits,psp-allowed-users
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - env:
            - name: TARGET
              value: Knative World
          image: otomi/nodejs-helloworld:v1.2.12
