groups:
  - name: ssl-expiry.rules
    rules:
      - alert: EssentEdSSLCertExpiringSoon
        expr: probe_ssl_earliest_cert_expiry{job="probe-essent-ed"} - time() < 86400 * 30
        for: 10m
        labels:
          severity: warning
        annotations:
          description: SSL certificate is expiring in 30 days. Please inform Wipro to renew.
          summary: SSL certificate is expiring in 30 days.
      - alert: K8sWildcardSSLCertExpiringSoon
        expr: probe_ssl_earliest_cert_expiry{job="probe-monitoring"} - time() < 86400 * 30
        for: 10m
        labels:
          severity: warning
        annotations:
          description: SSL certificate is expiring in 30 days. Please inform Wipro to renew.
          summary: SSL certificate is expiring in 30 days.
      - alert: EssentEdSSLCertExpiringSoon
        expr: probe_ssl_earliest_cert_expiry{job="probe-essent-ed"} - time() < 86400 * 7
        for: 10m
        labels:
          severity: critical
        annotations:
          description: SSL certificate is expiring in 7 days! Please inform Wipro to renew ASAP!
          summary: SSL certificate is expiring in 7 days!
      - alert: K8sWildcardSSLCertExpiringSoon
        expr: probe_ssl_earliest_cert_expiry{job="probe-monitoring"} - time() < 86400 * 7
        for: 10m
        labels:
          severity: critical
        annotations:
          description: SSL certificate is expiring in 7 days! Please inform Wipro to renew ASAP!
          summary: SSL certificate is expiring in 7 days!
