{{- if .Values.additionalPrometheusRulesMap }}
{{- range $prometheusRuleName, $prometheusRule := .Values.additionalPrometheusRulesMap }}
apiVersion: {{ printf "%s/v1" ($.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: PrometheusRule
metadata:
  name: {{ template "prometheus-operator.name" $ }}-{{ $prometheusRuleName }}
  labels:
    app: {{ template "prometheus-operator.name" $ }}
{{ include "prometheus-operator.labels" $ | indent 4 }}
    {{- if $prometheusRule.additionalLabels }}
{{ toYaml $prometheusRule.additionalLabels | indent 4 }}
    {{- end }}
spec:
  groups:
{{ toYaml $prometheusRule.groups| indent 4 }}
---
{{- end }}
{{- else }}
{{- range .Values.additionalPrometheusRules }}
apiVersion: {{ printf "%s/v1" ($.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: PrometheusRule
metadata:
  name: {{ template "prometheus-operator.name" $ }}-{{ .name }}
  labels:
    app: {{ template "prometheus-operator.name" $ }}
{{ include "prometheus-operator.labels" $ | indent 4 }}
    {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 4 }}
    {{- end }}
spec:
  groups:
{{ toYaml .groups| indent 4 }}
---
{{- end }}
{{- end }}
