{{- $v := .Values }}
{{ $namespaces := prepend $v.siblingNamespaces .Release.Namespace }}
{{- range $ns := $namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" $ | nindent 2 }}
  name: cluster-admin-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" $ | nindent 2 }}
  name: admin-team-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-team
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" $ | nindent 2 }}
  name: unprivileged-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unprivileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $ns }}
---
{{- end }}