{{- $v := .Values }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" . | nindent 2 }}
  name: {{ template "customer-ns.fullname" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
---
{{- range $ns := $v.siblingNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" . | nindent 2 }}
  name: {{ template "customer-ns.fullname" . }}-sibling
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "customer-ns.labels" . | nindent 2 }}
  name: {{ template "customer-ns.fullname" . }}-unpriviliged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:unprivileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
---


