apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "customer-ns.labels" . | nindent 2 }}
  name: {{ template "customer-ns.fullname" . }}-admin
rules:
   - apiGroups:
       - '*'
     resources:
       - '*'
     verbs:
       - '*'