{{- if .Values.persistence.enabled }}
{{- $registry := .Values.persistence.persistentVolumeClaim.registry -}}
{{- if and (not $registry.existingClaim) (eq .Values.persistence.imageChartStorage.type "filesystem") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.registry" . }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ toYaml .Values.customerLabels | indent 4 }}
{{ include "harbor.labels" . | indent 4 }}
    component: registry
spec:
  accessModes: 
    - {{ $registry.accessMode }}
  resources:
    requests:
      storage: {{ $registry.size }}
  {{- if $registry.storageClass }}
    {{- if eq "-" $registry.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $registry.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}