{{- $v := .Values }}
{{- if $v.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := $v.env }}
  {{$key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- if $v.init.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := $v.init.env }}
  {{$key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- range $location, $content := $v.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ include "fileConfigMapName" $location }}
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{ include "fileConfigMapName" $location }}: {{- toYaml $content | quote | nindent 2 }} 
---
{{- end }}
