{{- $v := .Values }} 
{{- if eq $v.type "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if eq ($v.runPolicy | default "OnSpecChange") "Always" }}
  name: {{ .Release.Name }}{{ join "-" (list $v.name uuidv4) | trunc 63 }}
  {{- else }}
  name: {{ .Release.Name }}
  {{- end }}
  labels: {{- include "jobs.labels" . | nindent 4 }}
spec: {{- include "podspec" . | nindent 2 }}
---
{{- end }}
