
{{- $v := .Values }}
{{- if $v.nativeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "jobs.labels" $ | nindent 4 }}
  name: {{ .Release.Name }}
data:
{{- range $key, $val := $v.nativeSecrets }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end }}
---
{{- end }}
{{- if $v.init.nativeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "jobs.labels" $ | nindent 4 }}
  name: {{ .Release.Name }}-init
data:
{{- range $key, $val := $v.init.nativeSecrets }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end }}
---
{{- end }}