{{- $v := .Values }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-sec-staging
    http01: {}
    dns01:
      providers:
      {{- if $v.provider.cloudDns.enabled }}
      - name: cloud-dns-provider
        clouddns:
          project: {{ $v.provider.cloudDns.projectId }}
          serviceAccountSecretRef:
            name: cloud-dns-key
            key: key.json
      {{- end }}