apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-files
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  index.html: |-
{{ include "html" . | nindent 4 }}