bases:
  - snippets/defaults.yaml

environments:
  default:
    values:
      - ../values/default.yaml
      - ../values/otomi.yaml

releases:
  - name: istio
    installed: true
    namespace: istio-system
    chart: ../charts/istio
    values:
    - ../values/istio/istio.gotmpl
    # - ../values/istio/istio-sds-auth.yaml
    # - ../values/istio/istio-googleca.yaml
