bases:
  - snippets/defaults.yaml

environments:
  default:
    values:
      - ../values/default.yaml
      - ../values/otomi.yaml

releases:
  - name: knative-init
    installed: true
    namespace: default
    chart: /tmp/charts/knative
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "../bin/skeleton-chart.sh"
        args: ["knative", "create", "manifests", "--selector knative.dev/crd-install=true"]
      - events: ["cleanup"]
        showlogs: true
        command: "../bin/skeleton-chart.sh"
        args: ["knative", "{{`{{ .HelmfileCommand }}`}}", "manifests", "--selector knative.dev/crd-install=true"]

  - name: istio-init
    installed: true
    namespace: istio-system
    chart: ../charts/istio
    values:
    - ../values/istio/istio.gotmpl
