bases:
  - snippets/defaults.yaml

environments:
  default:
    values:
      - ../values/default.yaml
      - ../values/otomi.yaml

{{ readFile "snippets/templates.yaml" }}
releases:
  - name: index
    installed: true
    namespace: system
    <<: *default
  - name: drone
    installed: true
    namespace: system
    <<: *default
  - name: gitlab
    installed: false
    namespace: system
    <<: *default
