bases:
  - snippets/defaults.yaml
  - snippets/repos.yaml

environments:
  default:
    values:
      - ../values/default.yaml
      - ../values/otomi.yaml

{{ readFile "snippets/templates.yaml" }}
releases:
  - name: cert-manager
    installed: true
    namespace: ingress
    <<: *default
  - name: cert-manager-cluster-issuer
    installed: true
    namespace: ingress
    <<: *default
  - name: dex
    installed: false
    namespace: ingress
    <<: *default
  - name: nginx-ingress
    installed: true
    namespace: ingress
    <<: *default
  - name: oauth2-ingress
    installed: false
    namespace: ingress
    <<: *default
  - name: oauth2-proxy
    installed: true
    namespace: ingress
    <<: *default
