apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: system
  name: harbor
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---