apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: system
  name: docker-registry
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---