apiVersion: v1
appVersion: 1.16.0
description: Chart for the service index
engine: gotpl
home: http://www.nginx.org
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
keywords:
- nginx
- http
- web
- www
- reverse proxy
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: index
sources:
- https://github.com/bitnami/bitnami-docker-nginx
version: 3.4.0
