apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio:psp:unrestricted
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unrestricted
subjects:
- kind: ServiceAccount
  name: istio-init-service-account
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio:psp:unrestricted:istio-cni
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unrestricted
subjects:
- kind: ServiceAccount
  name: istio-cni
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio:psp:restricted
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted
subjects:
- kind: ServiceAccount
  name: istio-init-service-account
  namespace: istio-system
