apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:unprivileged
rules:
- apiGroups:
  - extensions
  resourceNames:
  - unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
